version: '2'
services:
  taroco-authentication-server:
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    volumes:
      - /data/logs/taroco-authentication-server/:/logs/taroco-authentication-server/
    networks:
      - taroco

  taroco-rbac:
    build:
      context: ./
      dockerfile: Dockerfile-rbac
    restart: always
    volumes:
      - /data/logs/taroco-rbac-service/:/logs/taroco-rbac-service/
    networks:
      - taroco

  taroco-admin:
    build:
      context: ./
      dockerfile: Dockerfile-admin
    restart: always
    ports:
      - 10001:10001
    volumes:
      - /data/logs/taroco-admin/:/logs/taroco-admin/
    networks:
      - taroco

  taroco-monitor:
    build:
      context: ./
      dockerfile: Dockerfile-monitor
    restart: always
    ports:
      - 10002:10002
    volumes:
      - /data/logs/taroco-monitor/:/logs/taroco-monitor/
    networks:
      - taroco

  taroco-gateway:
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    ports:
      - 10000:10000
    depends_on:
      - taroco-authentication-server
    volumes:
      - /data/logs/taroco-gateway/:/logs/taroco-gateway/
    networks:
      - taroco

networks:
  taroco:
